#define WIFI_MAX_RETRY_TIME_MILLISECONDS 5000
#define MQTT_MAX_RETRY_TIME_MILLISECONDS 5000

#define BUILTIN_LED_PIN 8

#define COMMAND_RESET_CONTROLLER "reset-controller"
#define COMMAND_RESET_SERVER "reset-server"