#define DEVICE_ANALOG_WRITE_RESOLUTION 255
#define DEVICE_ANALOG_READ_RESOLUTION 1023

#define INTERCOMM_SERIAL_BAUD_RATE 9600
#define INTERCOMM_SEPARATOR ":"

#define COMMAND_PING "ping"
#define COMMAND_SET_PUMPING_TIME_LIMIT "set-pumping-time-limit"
#define COMMAND_GET_PUMPING_TIME_LIMIT "get-pumping-time-limit"
#define COMMAND_GET_PENDING_TIME_FOR_PUMPING "get-pending-time-for-pumping"
#define COMMAND_PUMP_WATER "pump-water"
#define COMMAND_SET_SAMPLING_TIME "set-sampling-time"
#define COMMAND_GET_SAMPLING_TIME "get-sampling-time"
#define COMMAND_GET_PENDING_TIME_FOR_SAMPLING "get-pending-time-for-sampling"
#define COMMAND_GET_MEASUREMENTS "get-measurements"

#define RESPONSE_ERROR "error"
#define RESPONSE_PONG "pong"
#define RESPONSE_PUMPING_TIME_LIMIT "pumping-time-limit"
#define RESPONSE_PENDING_TIME_FOR_PUMPING "pending-time-for-pumping"
#define RESPONSE_SAMPLING_TIME "sampling-time"
#define RESPONSE_PENDING_TIME_FOR_SAMPLING "pending-time-for-sampling"
#define RESPONSE_MEASUREMENTS "measurements"

#define DEFAULT_SAMPLING_TIME_MS 60000
#define MIN_SAMPLING_TIME_MS 1000
#define MAX_SAMPLING_TIME_MS 3600000

#define PUMP_PIN 3
#define MIN_PUMPING_TIME_MS 5000
#define MAX_PUMPING_TIME_MS 15000
#define MIN_TIME_BETWEEN_PUMPING_MS 10000
#define MAX_TIME_BETWEEN_PUMPING_MS 3600000

#define DHT_PIN 2
#define DHT_TYPE DHT11

#define SEN0193_1_PIN A4
#define SEN0193_1_WATER_VALUE 250
#define SEN0193_1_AIR_VALUE 585

#define SEN0193_2_PIN A5
#define SEN0193_2_WATER_VALUE 245
#define SEN0193_2_AIR_VALUE 580

#define HCSR04_PIN_ECHO 6
#define HCSR04_PIN_TRIGGER 7
#define HCSR04_SENSOR_HEIGHT 9.0
#define HCSR04_MAX_LEVEL_HEIGHT 7.0
#define HCSR04_SIGNAL_DELAY_MICROSECONDS 10
#define HCSR04_SOUND_SPEED_CM_PER_MICROSECOND 0.034