#define WIFI_MAX_RETRY_TIME_MILLISECONDS 5000

#define MQTT_MAX_RETRY_TIME_MILLISECONDS 5000

#define MQTT_TOPIC_BASE "/oasis"

#define MQTT_TOPIC_MEASUREMENTS "/measurements"
#define MQTT_TOPIC_MEASUREMENTS_AIR "/air"
#define MQTT_TOPIC_MEASUREMENTS_AIR_TEMPERATURE "/temperature"
#define MQTT_TOPIC_MEASUREMENTS_AIR_RELATIVE_HUMIDITY "/relativeHumidity"
#define MQTT_TOPIC_MEASUREMENTS_WATER "/water"
#define MQTT_TOPIC_MEASUREMENTS_WATER_FLOW_RATE "/flowRate"
#define MQTT_TOPIC_MEASUREMENTS_WATER_VOLUME "/volume"
#define MQTT_TOPIC_MEASUREMENTS_PUMP "/pump"
#define MQTT_TOPIC_MEASUREMENTS_PUMP_STATE "/state"

#define MQTT_TOPIC_CONTROL "/control"
#define MQTT_TOPIC_CONTROL_PUMP "/pump"

#define MEASURING_INTERVAL_MILLISECONDS 2000

#define DHT11_PIN 4

#define YF_S401_PIN 16
#define YF_S401_VOLUME_PER_PULSE 0.17006803 // milliliters per pulse