#define WIFI_MAX_RETRY_TIME_MILLISECONDS 5000

#define MQTT_MAX_RETRY_TIME_MILLISECONDS 5000

#define MQTT_TOPIC_BASE "/oasis"

#define MQTT_TOPIC_MEASUREMENTS "/measurements"
#define MQTT_TOPIC_MEASUREMENTS_AIR "/air"
#define MQTT_TOPIC_MEASUREMENTS_AIR_TEMPERATURE "/temperature"
#define MQTT_TOPIC_MEASUREMENTS_AIR_RELATIVE_HUMIDITY "/relativeHumidity"
#define MQTT_TOPIC_MEASUREMENTS_PUMP "/pump"
#define MQTT_TOPIC_MEASUREMENTS_PUMP_STATE "/state"

#define MQTT_TOPIC_CONTROL "/control"
#define MQTT_TOPIC_CONTROL_PUMP "/pump"

#define MEASURING_INTERVAL_MILLISECONDS 2000
